# DSP Homework 1: Discrete Hidden Markov Model

override CFLAGS +=
override CXXFLAGS +=
override LDFLAGS +=

all: train test

clean:
	$(RM) -f *.o
	$(RM) -rf *.dSYM
	$(RM) -f train test

.PHONY: all clean
